python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train1/ test ../google.bin 1 > test1.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train2/ test ../google.bin 2 > test2.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train3/ test ../google.bin 3 > test3.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train4/ test ../google.bin 4 > test4.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train5/ test ../google.bin 5 > test5.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train6/ test ../google.bin 6 > test6.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train7/ test ../google.bin 7 > test7.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train8/ test ../google.bin 8 > test8.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train9/ test ../google.bin 9 > test9.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train10/ test ../google.bin 10 > test10.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train11/ test ../google.bin 11 > test11.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train12/ test ../google.bin 12 > test12.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train13/ test ../google.bin 13 > test13.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train14/ test ../google.bin 14 > test14.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train15/ test ../google.bin 15 > test15.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train16/ test ../google.bin 16 > test16.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train17/ test ../google.bin 17 > test17.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train18/ test ../google.bin 18 > test18.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train19/ test ../google.bin 19 > test19.out 2>&1
python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train20/ test ../google.bin 20 > test20.out 2>&1
