echo "Beginning 1" && rm -rf train1 && mkdir -p train1 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train1 train ../google.bin 1 > run1.out 2>&1
echo "Beginning 2" && rm -rf train2 && mkdir -p train2 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train2 train ../google.bin 2 > run2.out 2>&1
echo "Beginning 3" && rm -rf train3 && mkdir -p train3 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train3 train ../google.bin 3 > run3.out 2>&1
echo "Beginning 4" && rm -rf train4 && mkdir -p train4 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train4 train ../google.bin 4 > run4.out 2>&1
echo "Beginning 5" && rm -rf train5 && mkdir -p train5 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train5 train ../google.bin 5 > run5.out 2>&1
echo "Beginning 6" && rm -rf train6 && mkdir -p train6 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train6 train ../google.bin 6 > run6.out 2>&1
echo "Beginning 7" && rm -rf train7 && mkdir -p train7 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train7 train ../google.bin 7 > run7.out 2>&1
echo "Beginning 8" && rm -rf train8 && mkdir -p train8 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train8 train ../google.bin 8 > run8.out 2>&1
echo "Beginning 9" && rm -rf train9 && mkdir -p train9 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train9 train ../google.bin 9 > run9.out 2>&1
echo "Beginning 10" && rm -rf train10 && mkdir -p train10 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train10 train ../google.bin 10 > run10.out 2>&1
echo "Beginning 11" && rm -rf train11 && mkdir -p train11 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train11 train ../google.bin 11 > run11.out 2>&1
echo "Beginning 12" && rm -rf train12 && mkdir -p train12 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train12 train ../google.bin 12 > run12.out 2>&1
echo "Beginning 13" && rm -rf train13 && mkdir -p train13 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train13 train ../google.bin 13 > run13.out 2>&1
echo "Beginning 14" && rm -rf train14 && mkdir -p train14 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train14 train ../google.bin 14 > run14.out 2>&1
echo "Beginning 15" && rm -rf train15 && mkdir -p train15 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train15 train ../google.bin 15 > run15.out 2>&1
echo "Beginning 16" && rm -rf train16 && mkdir -p train16 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train16 train ../google.bin 16 > run16.out 2>&1
echo "Beginning 17" && rm -rf train17 && mkdir -p train17 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train17 train ../google.bin 17 > run17.out 2>&1
echo "Beginning 18" && rm -rf train18 && mkdir -p train18 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train18 train ../google.bin 18 > run18.out 2>&1
echo "Beginning 19" && rm -rf train19 && mkdir -p train19 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train19 train ../google.bin 19 > run19.out 2>&1
echo "Beginning 20" && rm -rf train20 && mkdir -p train20 && python2 -u model/pos_bilstm.py dataset/clickbait.in dataset/non_clickbait.in train20 train ../google.bin 20 > run20.out 2>&1
